### ISSUE TITLE
the test accuract is too low by using optical conv

### ISSUE THREAD

**Issue by liujing1995** [computational-imaging/opticalCNN#2]
I run python optical_corrlator.py, and I find the accuracy is very low by using optical conv . And FC works fun...
![image](https://user-images.githubusercontent.com/33244970/47012996-4644e100-d178-11e8-8e65-1056f1baf6c7.png)
 Could U help me?
Thanks!

**Comment by juliechchang** [comment]
Hi! If you use optical conv directly, it corresponds to an end-to-end optimization of the phase mask with a classification loss. We actually found that this didn't work as well as a two-step optimization. The general approach we used for the paper was to first optimize the kernel(s) without directly including the phase mask, then prepare a target PSF based on the kernel(s), and finally optimize a phase mask that could produce the target PSF. You could try following the quickdraw-16 classification example instead.
